### ISSUE TITLE
Debian systemd error

### ISSUE THREAD

**Issue by sergioasantiago** [bdangit/chef-influxdb#103] opened 2016-03-08 00:59 UTC
Debian Jessie
Chef 12.7.2
chef-influxdb cookbook 4.1.0

I'm trying to start influxdb service using the default config in Debian jessie, but I m getting the following error:

```
Starting Chef Client, version 12.7.2
Compiling Cookbooks...   
Recipe: delorean::influxdb
  * chef_gem[vault] action install (up to date)
  Converging 17 resources
  * apt_package[lsb-release] action install (up to date)
Recipe: influxdb::default
  * chef_gem[toml-rb] action install (up to date)
  * chef_gem[influxdb] action install (up to date)
  * apt_package[apt-transport-https] action install (up to date)
  * apt_repository[influxdb] action add
    * remote_file[/var/chef/cache/influxdb.key] action create (up to date)
    * execute[install-key influxdb.key] action run (skipped due to not_if)
    * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * execute[apt-get update] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/influxdb.list] action create (up to date)
     (up to date)
  * apt_package[influxdb] action install (up to date)
  * influxdb_config[/etc/init/influxdb.conf] action create
    * file[/etc/init/influxdb.conf] action create (up to date)
     (up to date)
  * service[influxdb] action enable

    ================================================================================
    Error executing action `enable` on resource 'service[influxdb]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - /sbin/status

    Resource Declaration:
    ---------------------
    # In /chef/docker-cookbooks/influxdb/recipes/default.rb

     39: service 'influxdb' do
     40:   action [:enable, :start]
     41: end

    Compiled Resource:   
    ------------------   
    # Declared in /chef/docker-cookbooks/influxdb/recipes/default.rb:39:in `from_file'

    service("influxdb") do
      action [:enable, :start]
      supports {:restart=>nil, :reload=>nil, :status=>nil}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "influxdb"
      pattern "influxdb" 
      declared_type :service
      cookbook_name :influxdb
      recipe_name "default"
    end
```

If I install upstart package in Debian, I m able to run the default recipe, but If I try to start the service, even if it doesn't throws any error, InfluxDB just doesn't start.

```
Starting Chef Client, version 12.7.2
Compiling Cookbooks...
Converging 1 resources
Recipe: mycookbook::influxdb
  * service[influxdb] action enable
    - enable service service[influxdb]
  * service[influxdb] action start
    - start service service[influxdb]

Running handlers:
Running handlers complete
Chef Client finished, 2/2 resources updated in 02 seconds

root@7b49e4f0e13b:/chef# ps auxw | grep influx
root     32655  0.0  0.0  12816  1692 ?        S+   00:58   0:00 grep influx
```

Any idea why it's happening? Any suggestion on how to work it around?

**Comment by rennhak** [comment] 2016-03-08 15:30
+1

**Comment by fishnix** [comment] 2016-03-09 16:56
I'm trying to reproduce this but Debian 8.3 is not available via bento yet and this issue doesn't seem to be reproducible in 8.2 or ubuntu 15.04.

**Comment by sergioasantiago** [comment] 2016-03-09 21:54
I m using a docker container. Maybe you can try, or vagrant

**Comment by sergioasantiago** [comment] 2016-03-09 21:55
I ll try to use the script mentioned in this [article](https://caffinc.github.io/2015/12/influxdb-service-ubuntu/) and add it to /etc/init.d

**Comment by sergioasantiago** [comment] 2016-03-10 01:32
I could manage to start it by adding this code to my recipe:

Here I just copy the [init](https://github.com/influxdb/influxdb/blob/master/scripts/init.sh) file from influxdb repository to node /etc/init.d/influxdb

```ruby
cookbook_file '/etc/init.d/influxdb' do
  source 'influxdb/init.sh'
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end
```

And here I just changed the owner of influxdb folder, as per this [link](https://github.com/influxdata/influxdb/issues/4824)

```ruby
directory '/var/lib/influxdb' do
  owner 'influxdb'
  group 'influxdb'
  mode '0755'
  action :create
end
```

And now this next block run successfully

```ruby
service 'influxdb' do
  action :restart
end
```

**Comment by bdangit** [comment] 2016-03-10 06:28
hi @sergioasantiago containers don't have access to systemd as somewhat described in the article.  If you want access to the systemd service, you can run the container with /sbin/init and in privileged mode.  This is what we did to be able to test this cookbook with kitchen-docker https://github.com/bdangit/chef-influxdb/blob/master/.kitchen-docker.yml#L30

I guess a question I have is why would you want to run influxdb in a container?

**Comment by rennhak** [comment] 2016-03-10 14:38
> I guess a question I have is why would you want to run influxdb in a container?

Keeping databases such as InfluxDB inside containers and its data in volumes is interesting in a world where you are trying to avoid static datacenter deployments (think: mesos, kubernetes, flocker). Naturally these containers are not really ethemeral, but at least contained and encapsulated from the guest system allowing easier management and usage in our SOA world.

**Comment by bdangit** [comment] 2016-03-11 06:09
@rennhak makes sense.  

So looking at the default recipe, we just install the package as is from whatever repo according to the platform that is detected by chef.  It might be possible to detect or feature flag how we want the package to be installed.

Will do a little digging. @fishnix any ideas?

**Comment by fishnix** [comment] 2016-03-11 15:47
I don't think this is a problem with the package @bdangit, I think it's an issue with this service definition in default.rb:

```
service 'influxdb' do
  action [:enable, :start]
end
```

We could try to add a guard if we detect docker, although that might not work for everyone.  Alternatively @sergioasantiago, you could not use default.rb and/or wrap it with something like https://github.com/thommay/chef-rewind until we have a solution that's not too hacky.

**Comment by sergioasantiago** [comment] 2016-03-11 15:47
I guess the problem here is because it's missing the init script. If you check my comments how I did it and how I managed to make it work. I guess maybe it needs some adjustments before integrate, but it's a good start.

**Comment by fishnix** [comment] 2016-03-11 15:51
@sergioasantiago I don't think it make sense to add that script, there should be a more broadly applicable solution.  Glad it's working for you! :+1:

**Comment by rennhak** [comment] 2016-03-11 18:18
Appreciate the help @bdangit @fishnix - thanks!

**Comment by bdangit** [comment] 2016-03-14 17:14
All, I don't think we should use `service` chef resource or the concept of starting up services within a docker container.  What we should do is use the docker container to start up the influxd binary and expose the necessary ports required by other docker containers or any other hosts.

With that, we can use chef to configure an image, but then that image can be started up.

**Comment by sergioasantiago** [comment] 2016-03-14 18:07
@bdangit  I'm not using chef to start the service after docker container is built. I'm using the chef start to start the service during build process, because I need to create the default users during building process.

**Comment by bdangit** [comment] 2016-03-14 18:42
i'm not following... chef start?

**Comment by sergioasantiago** [comment] 2016-03-14 19:06
Sorry, I meant ```service```

**Comment by bdangit** [comment] 2016-03-15 04:21
Hrmm.  Perhaps what we could do is to feature flag in the presence of docker is to be able to run influxd in the background without a full fledge service routine and the  that would allow any of the influxdb chef resources to be still be used.  Would that be fine?

**Comment by sergioasantiago** [comment] 2016-03-15 14:05
@bdangit indeed, it would solve my problem. The main problem here is, I just need to use chef resources (user, database, ....) during docker build. The hack that I've done helped me, since now I  have it working, but as @fishnix said, it should not be the best solution.

**Comment by bdangit** [comment] 2016-03-24 02:04
putting this as enhancement.  will take a look more when need to move to 0.11 of influx

**Comment by bdangit** [comment] 2016-03-28 16:34
@sergioasantiago 

Working on recreating your scenario by running the following test-kitchen scenario in Docker:

```yaml
  - name: debian-8.2-chef<%= chef_version %>
    driver_config:
      box: debian:8.2
      platform: debian
      provision_command:
        - apt-get install upstart -y
```

I use to run debian in privileged mode and started at `/sbin/init`.  I'm able to install the influxdb package; however, when it gets to the service start, its not able to detect the influxdb init script in `/etc/init.d/`.

Here's the package contents that was installed:

```
~$ dpkg -L influxdb
/.
/var
/var/log
/var/log/influxdb
/var/lib
/var/lib/influxdb
/usr
/usr/bin
/usr/bin/influxd
/usr/bin/influx_tsm
/usr/bin/influx_stress
/usr/bin/influx_inspect
/usr/bin/influx
/usr/lib
/usr/lib/influxdb
/usr/lib/influxdb/scripts
/usr/lib/influxdb/scripts/influxdb.service
/usr/lib/influxdb/scripts/init.sh
/usr/share
/usr/share/doc
/usr/share/doc/influxdb
/usr/share/doc/influxdb/changelog.Debian.gz
/etc
/etc/logrotate.d
/etc/logrotate.d/influxdb
/etc/influxdb
/etc/influxdb/influxdb.conf
```

Despite installing upstart before the provisioning, the package wants to install the influxdb.service.

**Comment by bdangit** [comment] 2016-03-28 16:40
and here's why the influxdb is trying to install the systemd setup instead of the init.d routines:

https://github.com/influxdata/influxdb/blob/5a59b6483b25e1025fd143d9a92acb59770f3d39/scripts/post-install.sh#L56-L64

**Comment by sergioasantiago** [comment] 2016-03-28 17:00
> when it gets to the service start, its not able to detect the influxdb init script in /etc/init.d/

I was getting this same issue. I could manage to solve using the steps mentioned above:

https://github.com/bdangit/chef-influxdb/issues/103#issuecomment-194606262

It has a link to a init.sh script that I copied and add some extra folder/permission, and everything worked.

**Comment by bdangit** [comment] 2016-03-28 19:06
okay, i have a kitchen docker setup that is setup as follows:

```yaml
  - name: debian-8.2-chef<%= chef_version %>
    driver_config:
      box: debian:8.2
      platform: debian
      provision_command:
        - apt-get update
        - apt-get remove --purge systemd -y
        - apt-get install upstart -y
    provisioner:
      require_chef_omnibus: <%= chef_version %>
```

I remove systemd and install upstart.  Now chef thinks it can only install the init.d service versus the systemd which is not typically avaliable on docker-machines (at least my image with docker-machine is Rhel/Centos with systemd).

With that said, I'm now interested in how you are provisioning your docker containers?  I've also did some best practice finding about the usage of docker images and now believe that we should not use chef to bake in configuration details for image creation.  We should have a "generic" image that has influxdb in it and that you would control the configuration at runtime (more or less when starting up the container).  Chef can be responsible for starting up containers and configuring them during convergence, but it should not be involved to converge stuff inside the docker container.

Here is an influxdb image that you could start with that allows you to do what you need --https://hub.docker.com/r/tutum/influxdb/

I'll probably end my investigation in here and mark it as won't fix as thats not the intention of this cookbook.  Thoughts @fishnix / @sergioasantiago ?

**Comment by sergioasantiago** [comment] 2016-03-28 23:06
I agree with your testimonial,  but we have a slightly problem. You are suggesting using a pre-built  docker images, but in this way we will tied to docker, which is opposite the case that we uses. We currently uses docker but in the future we can use `potato's containers`, in that way If I need to migrate my system to `potato's container` I can keep using all my chef cookbooks. So currently my Dockerfile is dummy like this:

```
FROM debian:lastest

RUN curl -sL https://www.opscode.com/chef/install.sh | bash -

ADD ./build/chef/ /chef/

RUN cd /chef && chef-solo -c solo.rb -j nodes/docker-influxdb.json

RUN rm -rf /chef/
```

It will install and run my chef cookbook, giving me as a result a well built docker image, with influxdb configured.

**Comment by rennhak** [comment] 2016-03-29 11:48
> potato's container

Loose coupling to stay flexible enough when using other container engines such as CoreOS rkt, LXC etc.

**Comment by bdangit** [comment] 2016-04-04 17:01
@sergioasantiago / @rennhak 

For this to work with chef generically, we'll have to make a PR up to influxdb and have the package detect if its trying to install in a container or not.

**Comment by bdangit** [comment] 2016-04-04 17:06
https://github.com/influxdata/influxdb/issues/6198

**Comment by sergioasantiago** [comment] 2016-04-04 21:09
:+1:

**Comment by rennhak** [comment] 2016-04-05 12:58
:+1:

**Comment by fishnix** [comment] 2016-04-13 13:24
nice work @bdangit :+1:

**Comment by bdangit** [comment] 2016-07-15 14:57
hey gang, just want to let you know that Habitat is aimmed to solve this problem of application and configuration into a docker container if you please.  You may want to check it out.   https://github.com/chef/chefops-plans/tree/master/influxdb

https://www.habitat.sh/

**Comment by sergioasantiago** [comment] 2016-07-15 15:00
:+1:  thanks

**Comment by fishnix** [comment] 2016-07-15 15:01
thanks @bdangit ive been playing with habitat a bit myself, pretty cool 👍

**Comment by bdangit** [comment] 2016-11-30 15:49
*all* influxdb maintainers are asking if we still need support https://github.com/influxdata/influxdb/issues/6198#issuecomment-263897217.

After having to go through the motions of playing with containers a lot more, I'm inclined to say we shouldn't be running our containers using the "service" scripts.  We also should separate any configuration of data/schemas/and anything alike away from the actual running service (influxd).

The right model is stand up your datastore layer with the right volume mounts.  Then stand up "micro-service" or "job" that can administrate your datastore.  That way when a new influxd binary comes out -- you would just need to swap in this container with the same data volume mounts as before.  Persistence data hardly changes (unless due to datastore api compatibility issues) but the service layer will change and should be free to change.

With that said, for this cookbook, I would not recommend this cookbook be used for building out or maintaining containers.  There are just better methods one of which is through Habitat.  Please let me know your thoughts by the end of week.

**Comment by bdangit** [comment] 2016-12-05 18:07
last call to make peace with this...I'll close this out this Wednesday if no one speaks up.

**Comment by sergioasantiago** [comment] 2016-12-05 20:10
ok I understand your point, feel free to close.

Thanks!

**Comment by bdangit** [comment] 2016-12-08 08:19
closing.  thank you all!

**Closed by bdangit** 2016-12-08 08:19 UTC
Labels: enhancement
